/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v0/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description The project's accounts: staff list and read all of them, anybody else signed in only their own,
         *     and a signed-in user edits their own through `me`.
         */
        get: operations["users_list"];
        put?: never;
        /**
         * @description The project's accounts: staff list and read all of them, anybody else signed in only their own,
         *     and a signed-in user edits their own through `me`.
         */
        post: operations["users_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/users/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description The project's accounts: staff list and read all of them, anybody else signed in only their own,
         *     and a signed-in user edits their own through `me`.
         */
        get: operations["users_retrieve"];
        /**
         * @description The project's accounts: staff list and read all of them, anybody else signed in only their own,
         *     and a signed-in user edits their own through `me`.
         */
        put: operations["users_update"];
        post?: never;
        /**
         * @description The project's accounts: staff list and read all of them, anybody else signed in only their own,
         *     and a signed-in user edits their own through `me`.
         */
        delete: operations["users_destroy"];
        options?: never;
        head?: never;
        /**
         * @description The project's accounts: staff list and read all of them, anybody else signed in only their own,
         *     and a signed-in user edits their own through `me`.
         */
        patch: operations["users_partial_update"];
        trace?: never;
    };
    "/v0/users/{id}/history/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description One object's history, paginated, newest first - see HistoryMixin's own docstring for query params. */
        get: operations["users_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/users/history/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description History across every instance of the model (or scoped to `self.get_queryset()` - see
         *     `history_list_scoped_to_queryset`), paginated, newest first, restricted by
         *     `history_list_permission_classes` - see HistoryMixin's own docstring for query params.
         */
        get: operations["users_history_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description The project's accounts: staff list and read all of them, anybody else signed in only their own,
         *     and a signed-in user edits their own through `me`.
         */
        get: operations["users_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description How a user changes their own language preference (or name) - username/email stay
         *     untouchable here too, via UserSerializer's own create_only_fields.
         */
        patch: operations["users_me_partial_update"];
        trace?: never;
    };
    "/v0/users/me/reauthentication/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description How the signed-in person can prove it is them, for the page an act sends them to. */
        get: operations["users_me_reauthentication_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {unknown} */
        Blank: "";
        PaginatedUserHistoryList: {
            /**
             * @description Total number of items available.
             * @example 1102
             */
            count: number;
            /**
             * @description Number of results to return per page.
             * @example 100
             */
            page_size: number;
            /**
             * @description Total number of pages.
             * @example 17
             */
            total_pages: number;
            results: components["schemas"]["UserHistory"][];
        };
        PaginatedUserList: {
            /**
             * @description Total number of items available.
             * @example 1102
             */
            count: number;
            /**
             * @description Number of results to return per page.
             * @example 100
             */
            page_size: number;
            /**
             * @description Total number of pages.
             * @example 17
             */
            total_pages: number;
            results: components["schemas"]["User"][];
        };
        /**
         * @description `BaseSerializer` plus everything that is about a model - see each mixin's own docstring for what
         *     it adds: ModelSerializerRegistryMixin (model -> serializer lookup), FieldGuardsOnSaveMixin (the
         *     current viewset's field guards run inside `save()`, before the write), CreateOnlyFieldsMixin
         *     (`Meta.create_only_fields`), WriteOnlyFieldsMixin (`Meta.write_only_fields`),
         *     FlattenedOneToOneMixin (`Meta.flattened_one_to_one_fields`).
         *
         *     Pick and compose the individual mixins directly instead, if a project doesn't want all of this.
         */
        PatchedUserRequest: {
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username?: string;
            /** Email address */
            email?: string;
            first_name?: string;
            last_name?: string;
            /** @description The language this user chose for the interface, or blank to follow their browser's. */
            language?: components["schemas"]["UserLanguage"] | components["schemas"]["Blank"];
        };
        /** @description One way to prove it is you - see `ways_to_prove()`. Only the fields its flow carries are sent. */
        ReauthenticationFlow: {
            id: string;
            types?: string[];
            providers?: components["schemas"]["ReauthenticationProvider"][];
            /** Format: email */
            email?: string;
        };
        ReauthenticationProvider: {
            id: string;
            name: string;
        };
        /**
         * @description `BaseSerializer` plus everything that is about a model - see each mixin's own docstring for what
         *     it adds: ModelSerializerRegistryMixin (model -> serializer lookup), FieldGuardsOnSaveMixin (the
         *     current viewset's field guards run inside `save()`, before the write), CreateOnlyFieldsMixin
         *     (`Meta.create_only_fields`), WriteOnlyFieldsMixin (`Meta.write_only_fields`),
         *     FlattenedOneToOneMixin (`Meta.flattened_one_to_one_fields`).
         *
         *     Pick and compose the individual mixins directly instead, if a project doesn't want all of this.
         */
        User: {
            /**
             * Format: uuid
             * @description Identifies this record. A UUIDv7, so ids sort roughly by when they were created.
             */
            readonly id: string;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /** Email address */
            email?: string;
            first_name?: string;
            last_name?: string;
            /** @description The language this user chose for the interface, or blank to follow their browser's. */
            language?: components["schemas"]["UserLanguage"] | components["schemas"]["Blank"];
            /**
             * Format: date-time
             * @description When the row was created, by the database's clock. Never changes.
             */
            readonly created_at: string;
            /**
             * Format: date-time
             * @description When the row last changed, by the database's clock.
             */
            readonly updated_at: string;
        };
        UserHistory: {
            readonly event_id: number;
            /** Format: date-time */
            readonly event_created_at: string;
            readonly action: string;
            readonly changes: unknown;
            /**
             * Format: uuid
             * @description Identifies this record. A UUIDv7, so ids sort roughly by when they were created.
             */
            readonly id: string;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /** Email address */
            email?: string;
            first_name?: string;
            last_name?: string;
            /** @description The language this user chose for the interface, or blank to follow their browser's. */
            language?: components["schemas"]["UserLanguage"] | components["schemas"]["Blank"];
            /**
             * Format: date-time
             * @description When the row was created, by the database's clock. Never changes.
             */
            readonly created_at: string;
            /**
             * Format: date-time
             * @description When the row last changed, by the database's clock.
             */
            readonly updated_at: string;
            readonly actor_id: string | null;
        };
        /** @enum {string} */
        UserLanguage: "en" | "tr";
        /**
         * @description `BaseSerializer` plus everything that is about a model - see each mixin's own docstring for what
         *     it adds: ModelSerializerRegistryMixin (model -> serializer lookup), FieldGuardsOnSaveMixin (the
         *     current viewset's field guards run inside `save()`, before the write), CreateOnlyFieldsMixin
         *     (`Meta.create_only_fields`), WriteOnlyFieldsMixin (`Meta.write_only_fields`),
         *     FlattenedOneToOneMixin (`Meta.flattened_one_to_one_fields`).
         *
         *     Pick and compose the individual mixins directly instead, if a project doesn't want all of this.
         */
        UserRequest: {
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /** Email address */
            email?: string;
            first_name?: string;
            last_name?: string;
            /** @description The language this user chose for the interface, or blank to follow their browser's. */
            language?: components["schemas"]["UserLanguage"] | components["schemas"]["Blank"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    users_list: {
        parameters: {
            query?: {
                /** @description Drop these fields from the response - applied last, wins over only=/include=. */
                exclude?: string[];
                /** @description Narrow the response to just these fields (dotted paths reach into nested serializers). */
                only?: string[];
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUserList"];
                };
            };
        };
    };
    users_create: {
        parameters: {
            query?: {
                /** @description Drop these fields from the response - applied last, wins over only=/include=. */
                exclude?: string[];
                /** @description Narrow the response to just these fields (dotted paths reach into nested serializers). */
                only?: string[];
            };
            header: {
                /** @description A UUID of the caller's choosing. Sending the same key with the same body again returns what the first attempt answered rather than doing the work twice. It belongs to the attempt, not to the call: mint a new one when the payload changes or once a submit succeeds. */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserRequest"];
                "multipart/form-data": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_retrieve: {
        parameters: {
            query?: {
                /** @description Drop these fields from the response - applied last, wins over only=/include=. */
                exclude?: string[];
                /** @description Narrow the response to just these fields (dotted paths reach into nested serializers). */
                only?: string[];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_update: {
        parameters: {
            query?: {
                /** @description Drop these fields from the response - applied last, wins over only=/include=. */
                exclude?: string[];
                /** @description Narrow the response to just these fields (dotted paths reach into nested serializers). */
                only?: string[];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserRequest"];
                "multipart/form-data": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_destroy: {
        parameters: {
            query?: {
                /** @description Drop these fields from the response - applied last, wins over only=/include=. */
                exclude?: string[];
                /** @description Narrow the response to just these fields (dotted paths reach into nested serializers). */
                only?: string[];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_partial_update: {
        parameters: {
            query?: {
                /** @description Drop these fields from the response - applied last, wins over only=/include=. */
                exclude?: string[];
                /** @description Narrow the response to just these fields (dotted paths reach into nested serializers). */
                only?: string[];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserRequest"];
                "multipart/form-data": components["schemas"]["PatchedUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_history: {
        parameters: {
            query?: {
                action?: "delete" | "insert" | "update";
                actor?: string;
                created_after?: string;
                created_before?: string;
                object_id?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUserHistoryList"];
                };
            };
        };
    };
    users_history_list: {
        parameters: {
            query?: {
                action?: "delete" | "insert" | "update";
                actor?: string;
                created_after?: string;
                created_before?: string;
                object_id?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUserHistoryList"];
                };
            };
        };
    };
    users_me_retrieve: {
        parameters: {
            query?: {
                /** @description Drop these fields from the response - applied last, wins over only=/include=. */
                exclude?: string[];
                /** @description Narrow the response to just these fields (dotted paths reach into nested serializers). */
                only?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_me_partial_update: {
        parameters: {
            query?: {
                /** @description Drop these fields from the response - applied last, wins over only=/include=. */
                exclude?: string[];
                /** @description Narrow the response to just these fields (dotted paths reach into nested serializers). */
                only?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserRequest"];
                "multipart/form-data": components["schemas"]["PatchedUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_me_reauthentication_list: {
        parameters: {
            query?: {
                /** @description Drop these fields from the response - applied last, wins over only=/include=. */
                exclude?: string[];
                /** @description Narrow the response to just these fields (dotted paths reach into nested serializers). */
                only?: string[];
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReauthenticationFlow"][];
                };
            };
        };
    };
}
