/**
 * Placeholder - regenerate for real once the backend is running:
 *   npx openapi-typescript http://api.<domain>/v0/schema/ -o src/schema.ts
 * This file was auto-generated by openapi-typescript. Do not make direct changes to the file.
 */

export interface paths {
  '/v0/users/': {
    get: {
      parameters: {
        query?: {
          page?: number
          page_size?: number
        }
      }
      responses: {
        200: {
          content: {
            'application/json': {
              count: number
              page_size: number
              total_pages: number
              results: components['schemas']['User'][]
            }
          }
        }
      }
    }
  }
  '/v0/users/me/': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['User']
          }
        }
      }
    }
  }
}

export interface components {
  schemas: {
    User: {
      id: string
      username: string
      email: string
      first_name: string
      last_name: string
      created_at: string
      updated_at: string
    }
  }
}
