/**
 * Placeholder - regenerate for real once the backend is running:
 *   npx openapi-typescript http://api.<domain>/v0/schema/ -o src/schema.ts
 * This file was auto-generated by openapi-typescript. Do not make direct changes to the file.
 */

export interface paths {
  '/v0/users/': {
    get: {
      parameters: {
        query?: {
          page?: number
          page_size?: number
        }
      }
      responses: {
        200: {
          content: {
            'application/json': {
              count: number
              page_size: number
              total_pages: number
              results: components['schemas']['User'][]
            }
          }
        }
      }
    }
  }
  '/v0/users/me/': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['User']
          }
        }
      }
    }
    patch: {
      // username/email are read-only past creation (UserSerializer's own create_only_fields) -
      // not offered here even though the backend silently ignores them if sent anyway.
      requestBody: {
        content: {
          'application/json': Partial<Pick<components['schemas']['User'], 'first_name' | 'last_name' | 'language'>>
        }
      }
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['User']
          }
        }
      }
    }
  }
  '/v0/users/{id}/history/': {
    get: {
      parameters: {
        path: { id: string }
        query?: components['schemas']['UserHistoryQuery'] & { object_id?: string }
      }
      responses: {
        200: {
          content: {
            'application/json': {
              count: number
              page_size: number
              total_pages: number
              results: components['schemas']['UserHistoryEvent'][]
            }
          }
        }
      }
    }
  }
  '/v0/users/history/': {
    get: {
      parameters: {
        // Every instance's history at once, restricted to superusers by default (HistoryMixin's
        // own history_list_permission_classes) - object_id narrows it back to one, same as the
        // per-object endpoint above, just without a path segment to imply that already.
        query?: components['schemas']['UserHistoryQuery'] & { object_id?: string }
      }
      responses: {
        200: {
          content: {
            'application/json': {
              count: number
              page_size: number
              total_pages: number
              results: components['schemas']['UserHistoryEvent'][]
            }
          }
        }
      }
    }
  }
}

export interface components {
  schemas: {
    User: {
      id: string
      username: string
      email: string
      first_name: string
      last_name: string
      // "" (never omitted, unlike the session payload's own version of this - see
      // apps/users/headless.py) means no preference; the browser's language is used instead.
      language: string
      created_at: string
      updated_at: string
    }
    UserHistoryQuery: {
      action?: 'insert' | 'update' | 'delete'
      // A string, not a number - User.id is a uuid7, not HistoryMixin's own assumed integer pk
      // (UserViewSet overrides the built-in actor filter's type to match - see its own comment).
      actor?: string
      created_after?: string
      created_before?: string
      page?: number
      page_size?: number
    }
    // One event from a tracked model's history (see isik's generic_history_serializer()) - every
    // tracked User field flattened at the top level, plus event metadata. "password" is tracked
    // but withheld (UserViewSet.history_withhold): absent here, its change still shows in `changes`
    // as [null, null].
    UserHistoryEvent: {
      id: string
      username: string
      email: string
      first_name: string
      last_name: string
      language: string
      is_staff: boolean
      is_active: boolean
      is_superuser: boolean
      last_login: string | null
      date_joined: string
      created_at: string
      updated_at: string
      event_id: number
      event_created_at: string
      action: 'insert' | 'update' | 'delete'
      changes: Record<string, [unknown, unknown]> | null
      actor_id: string | null
    }
  }
}
