# Generated by Django 6.0.8 on 2026-10-03 00:03

import apps.users.models.user
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
import django_lifecycle.mixins
import isik.django.apps.common.skippable_validators.mixin
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(db_comment="When the row was created, by the database's clock. A trigger refuses any change to it.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row was created, by the database's clock. Never changes.", verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_comment="When the row last changed, by the database's clock. Stamped by a trigger on every update.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row last changed, by the database's clock.", verbose_name='Updated At')),
                ('id', models.UUIDField(db_comment='Primary key: a UUIDv7 the application generates, so ids sort roughly by creation time.', db_index=True, default=uuid.uuid7, editable=False, help_text='Identifies this record. A UUIDv7, so ids sort roughly by when they were created.', primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=apps.users.models.user.language_choices, db_comment='A code from settings.LANGUAGES, or empty for no preference: Accept-Language decides then.', default='', help_text="The language this user chose for the interface, or blank to follow their browser's.", max_length=15)),
                ('terms_version', models.CharField(blank=True, db_comment='apps.users.terms.TERMS_VERSION when the account was created; empty if no documents existed.', default='', help_text='The version of the legal documents this user agreed to at signup, or blank if none were published.', max_length=64)),
                ('terms_accepted_at', models.DateTimeField(blank=True, db_comment='Set with terms_version at signup; null when there was nothing to agree to.', help_text='When this user agreed to the legal documents, or empty if none were published at signup.', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
                'swappable': 'AUTH_USER_MODEL',
                'constraints': [models.CheckConstraint(condition=models.Q(('language__in', ['en', 'tr']), ('language', ''), _connector='OR'), name='users_user_language_choices')],
            },
            bases=(isik.django.apps.common.skippable_validators.mixin.SkippableValidatorsMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(db_comment="When the row was created, by the database's clock. A trigger refuses any change to it.", db_default=django.db.models.functions.datetime.Now(), editable=False, help_text="When the row was created, by the database's clock. Never changes.", verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_comment="When the row last changed, by the database's clock. Stamped by a trigger on every update.", db_default=django.db.models.functions.datetime.Now(), editable=False, help_text="When the row last changed, by the database's clock.", verbose_name='Updated At')),
                ('id', models.UUIDField(db_comment='Primary key: a UUIDv7 the application generates, so ids sort roughly by creation time.', default=uuid.uuid7, editable=False, help_text='Identifies this record. A UUIDv7, so ids sort roughly by when they were created.', serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=apps.users.models.user.language_choices, db_comment='A code from settings.LANGUAGES, or empty for no preference: Accept-Language decides then.', default='', help_text="The language this user chose for the interface, or blank to follow their browser's.", max_length=15)),
                ('terms_version', models.CharField(blank=True, db_comment='apps.users.terms.TERMS_VERSION when the account was created; empty if no documents existed.', default='', help_text='The version of the legal documents this user agreed to at signup, or blank if none were published.', max_length=64)),
                ('terms_accepted_at', models.DateTimeField(blank=True, db_comment='Set with terms_version at signup; null when there was nothing to agree to.', help_text='When this user agreed to the legal documents, or empty if none were published at signup.', null=True)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='0f4c136aac51134b2cfd413f16a3fd6f012b0876', operation='UPDATE', pgid='pgtrigger_protect_created_at_3e06e', table='users_user', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW."updated_at" = NOW(); RETURN NEW;', hash='772925d019b1e0aedd0c67b2f9b10317bf1cdb55', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_4c63c', table='users_user', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_userevent" ("created_at", "date_joined", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "language", "last_login", "last_name", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "terms_accepted_at", "terms_version", "updated_at", "username") VALUES (NEW."created_at", NEW."date_joined", NEW."email", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."language", NEW."last_login", NEW."last_name", NEW."password", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."terms_accepted_at", NEW."terms_version", NEW."updated_at", NEW."username"); RETURN NULL;', hash='493f4ae39cb5f50d1121222221ceab5da820fa0d', operation='INSERT', pgid='pgtrigger_insert_insert_52e78', table='users_user', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "users_userevent" ("created_at", "date_joined", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "language", "last_login", "last_name", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "terms_accepted_at", "terms_version", "updated_at", "username") VALUES (NEW."created_at", NEW."date_joined", NEW."email", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."language", NEW."last_login", NEW."last_name", NEW."password", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."terms_accepted_at", NEW."terms_version", NEW."updated_at", NEW."username"); RETURN NULL;', hash='26470aa998ad9e9aaeff00e5fd02b0be68f21aa2', operation='UPDATE', pgid='pgtrigger_update_update_16e22', table='users_user', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_userevent" ("created_at", "date_joined", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "language", "last_login", "last_name", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "terms_accepted_at", "terms_version", "updated_at", "username") VALUES (OLD."created_at", OLD."date_joined", OLD."email", OLD."first_name", OLD."id", OLD."is_active", OLD."is_staff", OLD."is_superuser", OLD."language", OLD."last_login", OLD."last_name", OLD."password", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."terms_accepted_at", OLD."terms_version", OLD."updated_at", OLD."username"); RETURN NULL;', hash='5727ea445ad4dd32ea27a93719fb3bb6b9589180', operation='DELETE', pgid='pgtrigger_delete_delete_56c96', table='users_user', when='AFTER')),
        ),
    ]
