# Generated by Django 6.0.8 on 2026-10-04 23:35

import django.contrib.auth.models
import django.contrib.contenttypes.models
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('users', '0002_delete_default_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedContentType',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contenttypes.contenttype',),
            managers=[
                ('objects', django.contrib.contenttypes.models.ContentTypeManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProtectedPermission',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['pgh_obj', '-pgh_id'], name='users_usere_pgh_obj_009e36_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='protectedcontenttype',
            trigger=pgtrigger.compiler.Trigger(name='protect_content_type_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot delete rows from % table', TG_TABLE_NAME;", hash='bbf1359a505935cfe443f0e1ddbedf00c0b5532b', operation='DELETE', pgid='pgtrigger_protect_content_type_delete_bb62b', table='django_content_type', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='protectedpermission',
            trigger=pgtrigger.compiler.Trigger(name='protect_permission_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot delete rows from % table', TG_TABLE_NAME;", hash='bb7e85fdd4cc25d90a29cb7b19b2dca3003b8f4f', operation='DELETE', pgid='pgtrigger_protect_permission_delete_4602b', table='auth_permission', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='protectedpermission',
            trigger=pgtrigger.compiler.Trigger(name='protect_permission_identity', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."codename" IS DISTINCT FROM (NEW."codename") OR OLD."content_type_id" IS DISTINCT FROM (NEW."content_type_id"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='0f53d775d5dc6f7baacd6c50c3c61376c98625a9', operation='UPDATE', pgid='pgtrigger_protect_permission_identity_b4c64', table='auth_permission', when='BEFORE')),
        ),
    ]
