# Generated by Django 6.0.8 on 2026-10-05 03:56

import apps.common.schema_docs
import django.db.models.deletion
import django.db.models.functions.datetime
import django_lifecycle.mixins
import isik.django.apps.common.skippable_validators.mixin
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('users', '0003_stream_index_and_protected_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettingsEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('created_at', models.DateTimeField(db_comment="When the row was created, by the database's clock. A trigger refuses any change to it.", db_default=django.db.models.functions.datetime.Now(), editable=False, help_text="When the row was created, by the database's clock. Never changes.", verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_comment="When the row last changed, by the database's clock. Stamped by a trigger on every update.", db_default=django.db.models.functions.datetime.Now(), editable=False, help_text="When the row last changed, by the database's clock.", verbose_name='Updated At')),
                ('id', models.UUIDField(db_comment='Primary key: a UUIDv7 the application generates, so ids sort roughly by creation time.', default=uuid.uuid7, editable=False, help_text='Identifies this record. A UUIDv7, so ids sort roughly by when they were created.', serialize=False, verbose_name='ID')),
                ('login_policy', models.CharField(choices=[('everyone', 'Everyone'), ('staff', 'Staff and superusers'), ('superusers', 'Superusers only')], db_comment='Who may still sign in: everyone, staff (and superusers) or superusers only.', default='everyone', help_text='Raising it signs out everybody it no longer admits, straight away.', max_length=16, verbose_name='who may sign in')),
                ('singleton', models.BooleanField(db_comment='Always true and unique, so the table can hold at most one row.', default=True, editable=False, help_text=apps.common.schema_docs.NoHelpText(reason='Never editable and never serialized: an internal guard, not a value anybody reads.'))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('created_at', models.DateTimeField(db_comment="When the row was created, by the database's clock. A trigger refuses any change to it.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row was created, by the database's clock. Never changes.", verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_comment="When the row last changed, by the database's clock. Stamped by a trigger on every update.", db_default=django.db.models.functions.datetime.Now(), db_index=True, editable=False, help_text="When the row last changed, by the database's clock.", verbose_name='Updated At')),
                ('id', models.UUIDField(db_comment='Primary key: a UUIDv7 the application generates, so ids sort roughly by creation time.', db_index=True, default=uuid.uuid7, editable=False, help_text='Identifies this record. A UUIDv7, so ids sort roughly by when they were created.', primary_key=True, serialize=False, verbose_name='ID')),
                ('login_policy', models.CharField(choices=[('everyone', 'Everyone'), ('staff', 'Staff and superusers'), ('superusers', 'Superusers only')], db_comment='Who may still sign in: everyone, staff (and superusers) or superusers only.', default='everyone', help_text='Raising it signs out everybody it no longer admits, straight away.', max_length=16, verbose_name='who may sign in')),
                ('singleton', models.BooleanField(db_comment='Always true and unique, so the table can hold at most one row.', default=True, editable=False, help_text=apps.common.schema_docs.NoHelpText(reason='Never editable and never serialized: an internal guard, not a value anybody reads.'), unique=True)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('singleton', True)), name='site_settings_singleton'), models.CheckConstraint(condition=models.Q(('login_policy__in', ['everyone', 'staff', 'superusers'])), name='users_sitesettings_login_policy_choices')],
            },
            bases=(isik.django.apps.common.skippable_validators.mixin.SkippableValidatorsMixin, django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='sitesettings',
            trigger=pgtrigger.compiler.Trigger(name='protect_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='7ec236d76f008544c2fc88528f8c4b2a2d7da6ef', operation='UPDATE', pgid='pgtrigger_protect_created_at_328ab', table='users_sitesettings', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='sitesettings',
            trigger=pgtrigger.compiler.Trigger(name='stamp_updated_at', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW."updated_at" = NOW(); RETURN NEW;', hash='c6fb0cf6a5303514f2daf14bd6f985514b2af0c0', operation='UPDATE', pgid='pgtrigger_stamp_updated_at_e11c1', table='users_sitesettings', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='sitesettings',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_sitesettingsevent" ("created_at", "id", "login_policy", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "singleton", "updated_at") VALUES (NEW."created_at", NEW."id", NEW."login_policy", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."singleton", NEW."updated_at"); RETURN NULL;', hash='290f87907f5fd182e561f7ee4d6004d81ff24b9b', operation='INSERT', pgid='pgtrigger_insert_insert_7cba7', table='users_sitesettings', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='sitesettings',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "users_sitesettingsevent" ("created_at", "id", "login_policy", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "singleton", "updated_at") VALUES (NEW."created_at", NEW."id", NEW."login_policy", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."singleton", NEW."updated_at"); RETURN NULL;', hash='18a1e816d347e582c547fce8788c2c094e9e5e7b', operation='UPDATE', pgid='pgtrigger_update_update_97b17', table='users_sitesettings', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='sitesettings',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_sitesettingsevent" ("created_at", "id", "login_policy", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "singleton", "updated_at") VALUES (OLD."created_at", OLD."id", OLD."login_policy", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."singleton", OLD."updated_at"); RETURN NULL;', hash='87dafb38c2ab05c03ceba526abb661b95470da17', operation='DELETE', pgid='pgtrigger_delete_delete_8b1e0', table='users_sitesettings', when='AFTER')),
        ),
        migrations.AddField(
            model_name='sitesettingsevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='sitesettingsevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='users.sitesettings'),
        ),
        migrations.AddIndex(
            model_name='sitesettingsevent',
            index=models.Index(fields=['pgh_obj', '-pgh_id'], name='users_sites_pgh_obj_ec3acf_idx'),
        ),
    ]
