/**
 * Placeholder - regenerate for real once the backend is running:
 *   npx openapi-typescript http://auth.<domain>/v0/openapi.yaml -o src/schema.ts
 * (allauth.headless serves its own spec when HEADLESS_SERVE_SPECIFICATION is on.)
 * This file was auto-generated by openapi-typescript. Do not make direct changes to the file.
 *
 * The /v0/app/v1/* entries below are hand-written the same way, for AppAuthApi (src/app.ts).
 * allauth's own openapi.yaml only has one templated {client} path per operation - with both
 * HEADLESS_CLIENTS (browser and app, the default) enabled, its schema endpoint leaves that
 * template unresolved rather than emitting two concrete paths. A real regeneration will need to
 * expand '/v0/{client}/v1/...' into the browser/app pairs by hand (or restrict HEADLESS_CLIENTS to
 * one client per regeneration run) - openapi-typescript run against the live spec as-is will not
 * reproduce this file's shape.
 */

type User = {
  id: string
  username: string
  email: string
  // Absent when unset (allauth's own DefaultHeadlessAdapter drops empty/None fields rather than
  // serving "" - see the backend's apps/users/headless.py), not just "" - browser fallback applies.
  language?: string
  // allauth's own: false for an account made through a social provider, which never set one.
  has_usable_password?: boolean
}

type Session = {
  id: number
  ip: string
  is_current: boolean
  user_agent: string
  created_at: number
  // Only present when USERSESSIONS_TRACK_ACTIVITY is on - off by default (see settings.py).
  last_seen_at?: number
}

type EmailAddress = { email: string; primary: boolean; verified: boolean }
type ProviderAccount = { id: number; provider: { id: string; name: string }; uid: string; display: { name: string } }

// `types` only on mfa_authenticate: the factors this user can answer the challenge with.
type Flow = { id: string; is_pending?: boolean; providers?: string[]; types?: AuthenticatorType[] }
type SessionData = { user: User; methods?: unknown[] }
type SessionMeta = { is_authenticated: boolean }
type SessionOk = { status: number; data: SessionData; meta: SessionMeta }
type SessionErr = { status: number; data?: { flows: Flow[] }; meta?: SessionMeta }
// The app client's counterpart to SessionOk/SessionMeta: identical shape, plus the session token -
// a browser gets its session key back as a cookie, an app client gets it here instead, in the body.
type AppSessionMeta = SessionMeta & { session_token?: string }
type AppSessionOk = { status: number; data: SessionData; meta: AppSessionMeta }
type AppSessionErr = { status: number; data?: { flows: Flow[] }; meta?: AppSessionMeta }
type AuthenticatorType = 'totp' | 'recovery_codes' | 'webauthn'
// One row of account/authenticators. id/name only on a passkey, the counts only on recovery codes.
type Authenticator = {
  type: AuthenticatorType
  created_at: number
  last_used_at: number | null
  id?: number
  name?: string
  is_passwordless?: boolean
  total_code_count?: number
  unused_code_count?: number
}
// unused_codes only while they may still be shown - MFA_RECOVERY_CODES_SHOW_ONCE hides them after.
type RecoveryCodes = Authenticator & { total_code_count: number; unused_code_count: number; unused_codes?: string[] }
type ConfigOk = {
  status: number
  data: { mfa?: { supported_types: AuthenticatorType[]; passkey_login_enabled: boolean } }
}
// WebAuthn's own options as JSON, which @isikk/core/webauthn turns into what the browser takes.
type WebAuthnCreationOptions = { publicKey: PublicKeyCredentialCreationOptionsJSON }
type WebAuthnRequestOptions = { publicKey: PublicKeyCredentialRequestOptionsJSON }
// A 404 that still carries what is needed to enroll: allauth answers "no TOTP yet" with a fresh secret.
type TOTPNotFound = { status: number; meta: { secret: string; totp_url: string } }
// allauth headless's flat validation-error shape ({errors: [{code, param, message}]}) - distinct
// from SessionErr, which is the 401 "pending flow" shape these 400s never take.
type ValidationErr = { status: number; errors: { code: string; param?: string; message: string }[] }

export interface paths {
  '/v0/browser/v1/auth/session': {
    get: { responses: { 200: { content: { 'application/json': SessionOk } }; 401: { content: { 'application/json': SessionErr } } } }
    delete: { responses: { 200: { content: { 'application/json': SessionOk } } } }
  }
  '/v0/browser/v1/auth/login': {
    post: {
      requestBody: { content: { 'application/json': { username?: string; email?: string; password: string } } }
      responses: { 200: { content: { 'application/json': SessionOk } }; 400: { content: { 'application/json': unknown } } }
    }
  }
  '/v0/browser/v1/auth/signup': {
    post: {
      requestBody: { content: { 'application/json': { username: string; email: string; password: string } } }
      responses: { 200: { content: { 'application/json': SessionOk } }; 401: { content: { 'application/json': SessionErr } } }
    }
  }
  '/v0/browser/v1/auth/reauthenticate': {
    post: {
      requestBody: { content: { 'application/json': { password: string } } }
      responses: {
        200: { content: { 'application/json': SessionOk } }
        400: { content: { 'application/json': ValidationErr } }
      }
    }
  }
  '/v0/browser/v1/auth/password/request': {
    post: { requestBody: { content: { 'application/json': { email: string } } }; responses: { 200: { content: { 'application/json': unknown } } } }
  }
  '/v0/browser/v1/auth/password/reset': {
    post: {
      requestBody: { content: { 'application/json': { key: string; password: string } } }
      // 200 only if resetting the password also completes a pending login - otherwise a *valid*
      // key still comes back 401: password changed, but the session isn't authenticated until the
      // user logs in with it. Same shape as signup/email-verify.
      responses: { 200: { content: { 'application/json': SessionOk } }; 401: { content: { 'application/json': SessionErr } } }
    }
  }
  '/v0/browser/v1/auth/email/verify': {
    post: {
      requestBody: { content: { 'application/json': { key: string } } }
      // 200 only if the verified email also completes a pending login (e.g. right after signup,
      // same session) - otherwise a *valid* key still comes back as 401: confirmed, but the
      // session isn't authenticated until the user logs in separately. Same shape as signup.
      responses: { 200: { content: { 'application/json': SessionOk } }; 401: { content: { 'application/json': SessionErr } } }
    }
  }
  '/v0/browser/v1/account/password/change': {
    post: {
      requestBody: { content: { 'application/json': { current_password?: string; new_password: string } } }
      responses: { 200: { content: { 'application/json': unknown } } }
    }
  }
  '/v0/browser/v1/account/email': {
    get: { responses: { 200: { content: { 'application/json': { data: EmailAddress[] } } } } }
    post: {
      requestBody: { content: { 'application/json': { email: string } } }
      responses: {
        200: { content: { 'application/json': { data: EmailAddress[] } } }
        400: { content: { 'application/json': ValidationErr } }
      }
    }
    put: { requestBody: { content: { 'application/json': { email: string } } }; responses: { 200: { content: { 'application/json': unknown } } } }
    patch: {
      requestBody: { content: { 'application/json': { email: string; primary: boolean } } }
      responses: {
        200: { content: { 'application/json': { data: EmailAddress[] } } }
        400: { content: { 'application/json': ValidationErr } }
      }
    }
    delete: {
      requestBody: { content: { 'application/json': { email: string } } }
      responses: {
        200: { content: { 'application/json': { data: EmailAddress[] } } }
        400: { content: { 'application/json': ValidationErr } }
      }
    }
  }
  '/v0/browser/v1/account/providers': {
    get: { responses: { 200: { content: { 'application/json': { data: ProviderAccount[] } } } } }
    delete: {
      requestBody: { content: { 'application/json': { provider: string; account: string } } }
      responses: {
        200: { content: { 'application/json': { data: ProviderAccount[] } } }
        400: { content: { 'application/json': ValidationErr } }
      }
    }
  }
  '/v0/browser/v1/auth/sessions': {
    get: { responses: { 200: { content: { 'application/json': { status: number; data: Session[] } } } } }
    delete: {
      requestBody: { content: { 'application/json': { sessions: number[] } } }
      responses: {
        200: { content: { 'application/json': { status: number; data: Session[] } } }
        401: { content: { 'application/json': SessionErr } }
      }
    }
  }
  '/v0/browser/v1/auth/provider/signup': {
    // The pending sociallogin's suggested user/account, fetched to prefill the "finish setting
    // up your account" form (see CompleteSignupForm.tsx) - a 409 here means there's no pending
    // signup at all (this page was reached directly, not via a real provider redirect).
    get: {
      responses: {
        200: { content: { 'application/json': { status: number; data: { user: User } } } }
        409: { content: { 'application/json': unknown } }
      }
    }
    post: {
      requestBody: { content: { 'application/json': { username: string; email: string; password?: string } } }
      // 200 if this also completes login; 401 if the account was created but needs a separate
      // login (mandatory email verification) - same shape as signup itself.
      responses: { 200: { content: { 'application/json': SessionOk } }; 401: { content: { 'application/json': SessionErr } } }
    }
  }
  '/v0/browser/v1/config': {
    get: { responses: { 200: { content: { 'application/json': ConfigOk } } } }
  }
  // Every write below needs a recent login: past ACCOUNT_REAUTHENTICATION_TIMEOUT allauth answers 401
  // with a pending reauthenticate flow instead.
  '/v0/browser/v1/account/authenticators': {
    get: { responses: { 200: { content: { 'application/json': { status: number; data: Authenticator[] } } } } }
  }
  '/v0/browser/v1/account/authenticators/totp': {
    get: {
      responses: {
        200: { content: { 'application/json': { status: number; data: Authenticator } } }
        404: { content: { 'application/json': TOTPNotFound } }
        // Enrolling is refused until the account's email is verified.
        409: { content: { 'application/json': ValidationErr } }
      }
    }
    post: {
      requestBody: { content: { 'application/json': { code: string } } }
      responses: {
        200: { content: { 'application/json': { status: number; data: Authenticator } } }
        400: { content: { 'application/json': ValidationErr } }
        401: { content: { 'application/json': SessionErr } }
      }
    }
    delete: {
      responses: {
        200: { content: { 'application/json': { status: number } } }
        401: { content: { 'application/json': SessionErr } }
      }
    }
  }
  '/v0/browser/v1/account/authenticators/recovery-codes': {
    get: {
      responses: {
        200: { content: { 'application/json': { status: number; data: RecoveryCodes } } }
        404: { content: { 'application/json': { status: number } } }
      }
    }
    post: {
      responses: {
        200: { content: { 'application/json': { status: number; data: RecoveryCodes } } }
        400: { content: { 'application/json': ValidationErr } }
        401: { content: { 'application/json': SessionErr } }
      }
    }
  }
  '/v0/browser/v1/account/authenticators/webauthn': {
    get: {
      responses: {
        200: { content: { 'application/json': { status: number; data: { creation_options: WebAuthnCreationOptions } } } }
        401: { content: { 'application/json': SessionErr } }
        409: { content: { 'application/json': ValidationErr } }
      }
    }
    post: {
      requestBody: { content: { 'application/json': { name?: string; credential: Record<string, unknown> } } }
      responses: {
        200: {
          content: {
            'application/json': { status: number; data: Authenticator; meta: { recovery_codes_generated: boolean } }
          }
        }
        400: { content: { 'application/json': ValidationErr } }
        401: { content: { 'application/json': SessionErr } }
      }
    }
    delete: {
      requestBody: { content: { 'application/json': { authenticators: number[] } } }
      responses: {
        200: { content: { 'application/json': { status: number } } }
        400: { content: { 'application/json': ValidationErr } }
        401: { content: { 'application/json': SessionErr } }
      }
    }
  }
  // The second step of a login whose password was right: the pending mfa_authenticate flow.
  '/v0/browser/v1/auth/2fa/authenticate': {
    post: {
      requestBody: { content: { 'application/json': { code: string } } }
      responses: {
        200: { content: { 'application/json': SessionOk } }
        400: { content: { 'application/json': ValidationErr } }
        401: { content: { 'application/json': SessionErr } }
      }
    }
  }
  '/v0/browser/v1/auth/webauthn/authenticate': {
    get: {
      responses: {
        200: { content: { 'application/json': { status: number; data: { request_options: WebAuthnRequestOptions } } } }
      }
    }
    post: {
      requestBody: { content: { 'application/json': { credential: Record<string, unknown> } } }
      responses: {
        200: { content: { 'application/json': SessionOk } }
        400: { content: { 'application/json': ValidationErr } }
        401: { content: { 'application/json': SessionErr } }
      }
    }
  }
  // Proving it is you again with a second factor rather than the password: the mfa_reauthenticate flow.
  '/v0/browser/v1/auth/2fa/reauthenticate': {
    post: {
      requestBody: { content: { 'application/json': { code: string } } }
      responses: {
        200: { content: { 'application/json': SessionOk } }
        400: { content: { 'application/json': ValidationErr } }
      }
    }
  }
  '/v0/browser/v1/auth/webauthn/reauthenticate': {
    get: {
      responses: {
        200: { content: { 'application/json': { status: number; data: { request_options: WebAuthnRequestOptions } } } }
      }
    }
    post: {
      requestBody: { content: { 'application/json': { credential: Record<string, unknown> } } }
      responses: {
        200: { content: { 'application/json': SessionOk } }
        400: { content: { 'application/json': ValidationErr } }
      }
    }
  }
  // The app client's own tree, same endpoints as their /v0/browser/v1 counterparts above (allauth
  // mounts both from one implementation) - AppAuthApi (src/app.ts) uses all of these.
  '/v0/app/v1/auth/session': {
    get: { responses: { 200: { content: { 'application/json': AppSessionOk } }; 401: { content: { 'application/json': AppSessionErr } } } }
    delete: { responses: { 200: { content: { 'application/json': AppSessionOk } } } }
  }
  '/v0/app/v1/auth/login': {
    post: {
      requestBody: { content: { 'application/json': { username?: string; email?: string; password: string } } }
      responses: { 200: { content: { 'application/json': AppSessionOk } }; 400: { content: { 'application/json': unknown } } }
    }
  }
  '/v0/app/v1/auth/signup': {
    post: {
      requestBody: { content: { 'application/json': { username: string; email: string; password: string } } }
      responses: { 200: { content: { 'application/json': AppSessionOk } }; 401: { content: { 'application/json': AppSessionErr } } }
    }
  }
  '/v0/app/v1/auth/2fa/authenticate': {
    post: {
      requestBody: { content: { 'application/json': { code: string } } }
      responses: {
        200: { content: { 'application/json': AppSessionOk } }
        400: { content: { 'application/json': ValidationErr } }
        401: { content: { 'application/json': AppSessionErr } }
      }
    }
  }
  '/v0/app/v1/auth/reauthenticate': {
    post: {
      requestBody: { content: { 'application/json': { password: string } } }
      responses: {
        200: { content: { 'application/json': AppSessionOk } }
        400: { content: { 'application/json': ValidationErr } }
      }
    }
  }
  '/v0/app/v1/auth/password/request': {
    post: { requestBody: { content: { 'application/json': { email: string } } }; responses: { 200: { content: { 'application/json': unknown } } } }
  }
  '/v0/app/v1/auth/password/reset': {
    post: {
      requestBody: { content: { 'application/json': { key: string; password: string } } }
      responses: { 200: { content: { 'application/json': AppSessionOk } }; 401: { content: { 'application/json': AppSessionErr } } }
    }
  }
  '/v0/app/v1/auth/email/verify': {
    post: {
      requestBody: { content: { 'application/json': { key: string } } }
      responses: { 200: { content: { 'application/json': AppSessionOk } }; 401: { content: { 'application/json': AppSessionErr } } }
    }
  }
  '/v0/app/v1/account/password/change': {
    post: {
      requestBody: { content: { 'application/json': { current_password?: string; new_password: string } } }
      responses: { 200: { content: { 'application/json': unknown } } }
    }
  }
  '/v0/app/v1/account/email': {
    get: { responses: { 200: { content: { 'application/json': { data: EmailAddress[] } } } } }
    post: {
      requestBody: { content: { 'application/json': { email: string } } }
      responses: {
        200: { content: { 'application/json': { data: EmailAddress[] } } }
        400: { content: { 'application/json': ValidationErr } }
      }
    }
    put: { requestBody: { content: { 'application/json': { email: string } } }; responses: { 200: { content: { 'application/json': unknown } } } }
    patch: {
      requestBody: { content: { 'application/json': { email: string; primary: boolean } } }
      responses: {
        200: { content: { 'application/json': { data: EmailAddress[] } } }
        400: { content: { 'application/json': ValidationErr } }
      }
    }
    delete: {
      requestBody: { content: { 'application/json': { email: string } } }
      responses: {
        200: { content: { 'application/json': { data: EmailAddress[] } } }
        400: { content: { 'application/json': ValidationErr } }
      }
    }
  }
  '/v0/app/v1/account/providers': {
    get: { responses: { 200: { content: { 'application/json': { data: ProviderAccount[] } } } } }
    delete: {
      requestBody: { content: { 'application/json': { provider: string; account: string } } }
      responses: {
        200: { content: { 'application/json': { data: ProviderAccount[] } } }
        400: { content: { 'application/json': ValidationErr } }
      }
    }
  }
  '/v0/app/v1/auth/sessions': {
    get: { responses: { 200: { content: { 'application/json': { status: number; data: Session[] } } } } }
    delete: {
      requestBody: { content: { 'application/json': { sessions: number[] } } }
      responses: {
        200: { content: { 'application/json': { status: number; data: Session[] } } }
        401: { content: { 'application/json': AppSessionErr } }
      }
    }
  }
  '/v0/app/v1/auth/provider/signup': {
    get: {
      responses: {
        200: { content: { 'application/json': { status: number; data: { user: User } } } }
        409: { content: { 'application/json': unknown } }
      }
    }
    post: {
      requestBody: { content: { 'application/json': { username: string; email: string; password?: string } } }
      responses: { 200: { content: { 'application/json': AppSessionOk } }; 401: { content: { 'application/json': AppSessionErr } } }
    }
  }
  // Token-based social login (Sign in with Apple / Google's native sign-in) - the mobile
  // counterpart to the browser's redirect-based auth/provider/redirect, which a native app has no
  // use for (no address bar to redirect). Same AppSessionOk/Err shape as login/signup: a first-ever
  // signup still lands in the same pending auth/provider/signup flow above, not automatically
  // authenticated (SOCIALACCOUNT_AUTO_SIGNUP is off).
  '/v0/app/v1/auth/provider/token': {
    post: {
      requestBody: {
        content: {
          'application/json': { provider: string; process: 'login'; token: Record<string, unknown> }
        }
      }
      responses: {
        200: { content: { 'application/json': AppSessionOk } }
        400: { content: { 'application/json': ValidationErr } }
        401: { content: { 'application/json': AppSessionErr } }
      }
    }
  }
}
