/**
 * Placeholder - regenerate for real once the backend is running:
 *   npx openapi-typescript http://auth.<domain>/v0/openapi.yaml -o src/schema.ts
 * (allauth.headless serves its own spec when HEADLESS_SERVE_SPECIFICATION is on.)
 * This file was auto-generated by openapi-typescript. Do not make direct changes to the file.
 *
 * The /v0/app/v1/* entries below are hand-written the same way, for AppAuthApi (src/app.ts).
 * allauth's own openapi.yaml only has one templated {client} path per operation - with both
 * HEADLESS_CLIENTS (browser and app, the default) enabled, its schema endpoint leaves that
 * template unresolved rather than emitting two concrete paths. A real regeneration will need to
 * expand '/v0/{client}/v1/...' into the browser/app pairs by hand (or restrict HEADLESS_CLIENTS to
 * one client per regeneration run) - openapi-typescript run against the live spec as-is will not
 * reproduce this file's shape.
 */

type User = {
  id: string
  username: string
  email: string
}

type Session = {
  id: number
  ip: string
  is_current: boolean
  user_agent: string
  created_at: number
  // Only present when USERSESSIONS_TRACK_ACTIVITY is on - off by default (see settings.py).
  last_seen_at?: number
}

type EmailAddress = { email: string; primary: boolean; verified: boolean }
type ProviderAccount = { id: number; provider: { id: string; name: string }; uid: string; display: { name: string } }

type Flow = { id: string; is_pending?: boolean; providers?: string[] }
type SessionData = { user: User; methods?: unknown[] }
type SessionMeta = { is_authenticated: boolean }
type SessionOk = { status: number; data: SessionData; meta: SessionMeta }
type SessionErr = { status: number; data?: { flows: Flow[] }; meta?: SessionMeta }
// The app client's counterpart to SessionOk/SessionMeta: identical shape, plus the session token -
// a browser gets its session key back as a cookie, an app client gets it here instead, in the body.
type AppSessionMeta = SessionMeta & { session_token?: string }
type AppSessionOk = { status: number; data: SessionData; meta: AppSessionMeta }
type AppSessionErr = { status: number; data?: { flows: Flow[] }; meta?: AppSessionMeta }
// allauth headless's flat validation-error shape ({errors: [{code, param, message}]}) - distinct
// from SessionErr, which is the 401 "pending flow" shape these 400s never take.
type ValidationErr = { status: number; errors: { code: string; param?: string; message: string }[] }

export interface paths {
  '/v0/browser/v1/auth/session': {
    get: { responses: { 200: { content: { 'application/json': SessionOk } }; 401: { content: { 'application/json': SessionErr } } } }
    delete: { responses: { 200: { content: { 'application/json': SessionOk } } } }
  }
  '/v0/browser/v1/auth/login': {
    post: {
      requestBody: { content: { 'application/json': { username?: string; email?: string; password: string } } }
      responses: { 200: { content: { 'application/json': SessionOk } }; 400: { content: { 'application/json': unknown } } }
    }
  }
  '/v0/browser/v1/auth/signup': {
    post: {
      requestBody: { content: { 'application/json': { username: string; email: string; password: string } } }
      responses: { 200: { content: { 'application/json': SessionOk } }; 401: { content: { 'application/json': SessionErr } } }
    }
  }
  '/v0/browser/v1/auth/password/request': {
    post: { requestBody: { content: { 'application/json': { email: string } } }; responses: { 200: { content: { 'application/json': unknown } } } }
  }
  '/v0/browser/v1/auth/password/reset': {
    post: {
      requestBody: { content: { 'application/json': { key: string; password: string } } }
      // 200 only if resetting the password also completes a pending login - otherwise a *valid*
      // key still comes back 401: password changed, but the session isn't authenticated until the
      // user logs in with it. Same shape as signup/email-verify.
      responses: { 200: { content: { 'application/json': SessionOk } }; 401: { content: { 'application/json': SessionErr } } }
    }
  }
  '/v0/browser/v1/auth/email/verify': {
    post: {
      requestBody: { content: { 'application/json': { key: string } } }
      // 200 only if the verified email also completes a pending login (e.g. right after signup,
      // same session) - otherwise a *valid* key still comes back as 401: confirmed, but the
      // session isn't authenticated until the user logs in separately. Same shape as signup.
      responses: { 200: { content: { 'application/json': SessionOk } }; 401: { content: { 'application/json': SessionErr } } }
    }
  }
  '/v0/browser/v1/account/password/change': {
    post: {
      requestBody: { content: { 'application/json': { current_password?: string; new_password: string } } }
      responses: { 200: { content: { 'application/json': unknown } } }
    }
  }
  '/v0/browser/v1/account/email': {
    get: { responses: { 200: { content: { 'application/json': { data: EmailAddress[] } } } } }
    post: {
      requestBody: { content: { 'application/json': { email: string } } }
      responses: {
        200: { content: { 'application/json': { data: EmailAddress[] } } }
        400: { content: { 'application/json': ValidationErr } }
      }
    }
    put: { requestBody: { content: { 'application/json': { email: string } } }; responses: { 200: { content: { 'application/json': unknown } } } }
    patch: {
      requestBody: { content: { 'application/json': { email: string; primary: boolean } } }
      responses: {
        200: { content: { 'application/json': { data: EmailAddress[] } } }
        400: { content: { 'application/json': ValidationErr } }
      }
    }
    delete: {
      requestBody: { content: { 'application/json': { email: string } } }
      responses: {
        200: { content: { 'application/json': { data: EmailAddress[] } } }
        400: { content: { 'application/json': ValidationErr } }
      }
    }
  }
  '/v0/browser/v1/account/providers': {
    get: { responses: { 200: { content: { 'application/json': { data: ProviderAccount[] } } } } }
    delete: {
      requestBody: { content: { 'application/json': { provider: string; account: string } } }
      responses: {
        200: { content: { 'application/json': { data: ProviderAccount[] } } }
        400: { content: { 'application/json': ValidationErr } }
      }
    }
  }
  '/v0/browser/v1/auth/sessions': {
    get: { responses: { 200: { content: { 'application/json': { status: number; data: Session[] } } } } }
    delete: {
      requestBody: { content: { 'application/json': { sessions: number[] } } }
      responses: {
        200: { content: { 'application/json': { status: number; data: Session[] } } }
        401: { content: { 'application/json': SessionErr } }
      }
    }
  }
  '/v0/browser/v1/auth/provider/signup': {
    // The pending sociallogin's suggested user/account, fetched to prefill the "finish setting
    // up your account" form (see CompleteSignupForm.tsx) - a 409 here means there's no pending
    // signup at all (this page was reached directly, not via a real provider redirect).
    get: {
      responses: {
        200: { content: { 'application/json': { status: number; data: { user: User } } } }
        409: { content: { 'application/json': unknown } }
      }
    }
    post: {
      requestBody: { content: { 'application/json': { username: string; email: string; password?: string } } }
      // 200 if this also completes login; 401 if the account was created but needs a separate
      // login (mandatory email verification) - same shape as signup itself.
      responses: { 200: { content: { 'application/json': SessionOk } }; 401: { content: { 'application/json': SessionErr } } }
    }
  }
  // The app client's own tree, same endpoints as their /v0/browser/v1 counterparts above (allauth
  // mounts both from one implementation) - only the three AppAuthApi (src/app.ts) actually uses.
  '/v0/app/v1/auth/session': {
    get: { responses: { 200: { content: { 'application/json': AppSessionOk } }; 401: { content: { 'application/json': AppSessionErr } } } }
    delete: { responses: { 200: { content: { 'application/json': AppSessionOk } } } }
  }
  '/v0/app/v1/auth/login': {
    post: {
      requestBody: { content: { 'application/json': { username?: string; email?: string; password: string } } }
      responses: { 200: { content: { 'application/json': AppSessionOk } }; 400: { content: { 'application/json': unknown } } }
    }
  }
  '/v0/app/v1/auth/signup': {
    post: {
      requestBody: { content: { 'application/json': { username: string; email: string; password: string } } }
      responses: { 200: { content: { 'application/json': AppSessionOk } }; 401: { content: { 'application/json': AppSessionErr } } }
    }
  }
}
